### ISSUE TITLE
Support Helm 3.7.0 and newer

### ISSUE THREAD

**Issue by ckotzbauer** [SamhammerAG/helm-action#6]
This release has breaking-changes to the OCI commands used here: https://github.com/helm/helm/releases/tag/v3.7.0

**Comment by agentschmitt** [comment]
maybe we should directly update to latest helm version we now skipped 3 versions:

- https://github.com/helm/helm/releases/tag/v3.10.0
  - Kubernetes 1.25 support
- https://github.com/helm/helm/releases/tag/v3.9.0
  - Kubernetes 1.24 support
- https://github.com/helm/helm/releases/tag/v3.8.0
  - OCI registries (final version)
  - Kubernetes 1.23 support
- https://github.com/helm/helm/releases/tag/v3.7.0
  - OCI registries (major changes)

**Comment by agentschmitt** [comment]
for the meanwhile i update the readme to use helm v.3.6
